=== Guidelines for document authors

Unlike a word processor like _Microsoft Word_, GBIF's documentation is stored in plain text files written in a lightweight markup language called https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc]. This approach means that:

* Authors need not worry about maintaining formatting.
* Changes to both the document's content and structure can be tracked and managed using general tools.
* The same source files can produce multiple outputs automatically, such as HTML and (as a convenience) PDF.
* The management and tracking translations is easier and more efficient. 

While this system does require learning some new tools, the ones we have chosen are widely used in the publishing, software development and translation communities. AsciiDoc is also relatively simple to work with and understand. If you've written or edited a Wikipedia article, you’ll have no problem with this format.

We've pulled out details for a few of the more common uses of AsciiDoc markup https://#[in the technical guidelines below] to give you a flavour of it, but the https://asciidoctor.org/docs/user-manual/[AsciiDoctor User Guide] provides a comprehensive reference on how to work with this language. You can direct questions, comments or concerns about this approach to mailto:communication@gbif.org[communication@gbif.org].
