[[panel]]
== Documentation Steering Panel

The Steering Panel consists of a volunteer group of experts that, in coordination with GBIF Secretariat staff, provides oversight and guidance for the selection and community-review of GBIF documentation.

=== Structure and operations
 
The panel consists of 8-10 members comprised of individuals from GBIF regions and the Secretariat staff. The panel meets (no more than quarterly) to discuss existing documentation and to provide recommendations to the GBIF Secretariat on commissioning high-priority guidance from subject-matter experts. 

=== Responsibilities

. Assist with setting annual priorities for documentation needs and make recommendations for calls for documentation as and when appropriate.
. Consult widely with other experts, institutions, initiatives and projects within the biodiversity informatics community at-large when considering updates to and for new documentation.
. Review and make recommendations regarding the documentation system for future sustainability.
. Participate in the vetting process to ensure that commissioned documentation is of high quality and serves the intended audiences.

=== Panel members

* Sharon Grant, chair (North America)
* Patricia Mergen, vice-chair (Europe and Central Asia)
* Pierre Radji (Africa)
* Maofang Luo (Asia)
* Paula Zermoglio (Latin American and the Caribbean)
* Chantel Hjubers (Oceania)
* Andrea Hahn (GBIF Secretariat)
* Dmitry Schigel (GBIF Secretariat)

=== GBIF Secretariat panel liasons

* Kyle Copas
* Laura Anne Russell
