== Documentation process and workflow

This document outlines the process by which the GBIF Secretariat will produce digital documentation. 

open participation: inclusive wider community, enable credit
open identities
open issues: recorded and addressed within an open repository
open interaction: possible training
open learning: new versions can be produced as correction , training and persistent provenance
open platforms

inclusive, transparent and accountable

The manuscript is fast-checked, and published on a network-based platform. Through a forum, others can leave commentaries.

Open peer-review oath

Principle 1. I will sign my name to my review
Principle 2. I will review with integrity
Principle 3. I will treat the review as a discourse with you; in particular, I will provide constructive criticism
Principle 4. I will be an ambassador for the practice of open science

Aleksic J, Alexa A, Attwood TK et al. (2015) An Open Science Peer Review Oath, v2. F1000Research 3: 271. https://doi.org/10.12688/f1000research.5686.2


=== Editorial panel prioritization and selection

GBIF Secretariat identifies candidate documents for revision as well as emerging topics for which the community could benefit from documentation. Editorial panel selects a tranche of four to five documents with recommendations on potential authors or author teams to approach. 

=== Commissioning document

Scope of work, contract.

=== Work begins

Timely execution, consultation with other experts as authors deem fit during the writing process (there will be a chance to get their input in the review process.

=== Submission of documentation

Submission format is agnostic, though final format is https://asciidoctor.org/docs/what-is-asciidoc/[Asciidoc]. 

=== Preliminary review by GBIF Secretariat

Staff conduct an initial review of the document's style and structure, checking it against the author guidelines and ensuring consistent conventions, spelling and approach. Internal subject-matter experts may be consulted. Substantive edits introduced at this point will be shared and reviewed with the author(s).

=== Preparation of draft publication

GitHub to HTML and PDF

=== Open-peer review

Secretariat staff issue an call to the community members to review and comment on the document, including guidance on preferred methods and modes of participation. 

=== . Revisions

Secretariat addresses minor and technical issues. Larger ones assigned to authors as GitHub issues.

Potential reviewers consider the invitation against their own expertise, conflicts of interest and availability. They then accept or decline. If possible, when declining, they might also suggest alternative reviewers.

=== . Publication


=== . Post-publication
